services:
  - type: web
    name: stagejhook-backend
    env: node
    plan: free
    rootDir: ./
    buildCommand: cd server && npm install && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        scope: project
      - key: MONGODB_URI
        scope: project
      - key: BLOB_READ_WRITE_TOKEN
        scope: project
      - key: FRONTEND_URL
        scope: project
